# Generated by Django 2.2.5 on 2021-09-20 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210918_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='houserule',
            new_name='house_rule',
        ),
    ]
