# Generated by Django 2.2.5 on 2021-09-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20210920_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house_rule',
            new_name='houserules',
        ),
    ]
